package com.co.videoclub.presentacion.swings;

import com.co.videoclub.controlador.OperacionesPeliculas;
import com.co.videoclub.controlador.OperacionesPeliculasImpl;
import com.co.videoclub.exception.BDException;
import java.util.List;
import javax.swing.JOptionPane;
import com.co.videoclub.persistencia.dto.Categoria;
import com.co.videoclub.persistencia.dto.Pelicula;
import com.co.videoclub.util.DateUtil;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author davigofr
 */
public class EditarPelicula extends javax.swing.JDialog {

    private OperacionesPeliculas operacionesPeli;
    private List<Categoria> categorias;
    private Pelicula peliculaSeleccionada;
    private final DateUtil dateUtil;
    
    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     */
    public EditarPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dateUtil = new DateUtil();
        this.jTADescripcionP.setLineWrap(true);
        this.jTADescripcionP.setWrapStyleWord(true);
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPEditarPelicula = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLNombreP = new javax.swing.JLabel();
        jTFNombreP = new javax.swing.JTextField();
        jLDuracionP = new javax.swing.JLabel();
        jTFDuracionP = new javax.swing.JTextField();
        jLDescripcionP = new javax.swing.JLabel();
        jAñoP = new javax.swing.JLabel();
        jTFAñoP = new javax.swing.JTextField();
        jLCategoriaP = new javax.swing.JLabel();
        jCBCategoriaP = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionP = new javax.swing.JTextArea();
        jLabelInformacion = new javax.swing.JLabel();
        jGuardarP = new javax.swing.JButton();
        jMBArchivo = new javax.swing.JMenuBar();
        jMFile = new javax.swing.JMenu();
        jMISalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar pelicula");
        setBounds(new java.awt.Rectangle(400, 150, 0, 0));
        setResizable(false);

        jLNombreP.setText("Nombre:");

        jLDuracionP.setText("Duracion (min):");

        jLDescripcionP.setText("Descripción:");

        jAñoP.setText("Año:");

        jTFAñoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAñoPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAñoPKeyTyped(evt);
            }
        });

        jLCategoriaP.setText("Categoria:");

        jTADescripcionP.setColumns(20);
        jTADescripcionP.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionP);

        jLabelInformacion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelInformacion.setText("Información de la pelicula");

        jGuardarP.setBackground(new java.awt.Color(255, 255, 255));
        jGuardarP.setText("Guardar");
        jGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEditarPeliculaLayout = new javax.swing.GroupLayout(jPEditarPelicula);
        jPEditarPelicula.setLayout(jPEditarPeliculaLayout);
        jPEditarPeliculaLayout.setHorizontalGroup(
            jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                .addComponent(jLDescripcionP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                        .addComponent(jLCategoriaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCategoriaP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                        .addComponent(jGuardarP)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                        .addComponent(jLNombreP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEditarPeliculaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLDuracionP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDuracionP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jAñoP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFAñoP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabelInformacion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPEditarPeliculaLayout.setVerticalGroup(
            jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                .addComponent(jLabelInformacion)
                .addGap(21, 21, 21)
                .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreP)
                    .addComponent(jTFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDuracionP)
                    .addComponent(jTFDuracionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAñoP)
                    .addComponent(jTFAñoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEditarPeliculaLayout.createSequentialGroup()
                        .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescripcionP)
                            .addGroup(jPEditarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCBCategoriaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLCategoriaP)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jGuardarP))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
        );

        jMFile.setText("Archivo");

        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMFile.add(jMISalir);

        jMBArchivo.add(jMFile);

        setJMenuBar(jMBArchivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEditarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPEditarPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFAñoPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAñoPKeyPressed

    }//GEN-LAST:event_jTFAñoPKeyPressed

    private void jTFAñoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAñoPKeyTyped
        
    }//GEN-LAST:event_jTFAñoPKeyTyped

    private void jGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarPActionPerformed
        try{
            int id = getPeliculaSeleccionada().getId();
            String nombre = jTFNombreP.getText();
            String fechaLanzamiento = jTFAñoP.getText();
            Date fechaConvertida = (fechaLanzamiento == null || fechaLanzamiento.isEmpty())
                        ? null : dateUtil.convertirStringADate(fechaLanzamiento);
            int duracion = Integer.valueOf(jTFDuracionP.getText());
            String descripcion = jTADescripcionP.getText();
            Categoria categoria = (Categoria)jCBCategoriaP.getSelectedItem();
            
            this.getOperacionesPeli().actualizarPelicula(id, nombre, fechaConvertida, duracion, descripcion, categoria);
            
            JOptionPane.showMessageDialog(this, "Se actualizó correctamente la pelicula",
                "Confirmación de actualización", JOptionPane.INFORMATION_MESSAGE);
        } catch(BDException ex){
            Logger.getLogger(EditarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar "
                + "la nueva pelicula, por favor contacte al administrador",
                "Error de persistencia de datos", JOptionPane.ERROR_MESSAGE);
        } catch(NumberFormatException | ClassCastException ex){
            Logger.getLogger(EditarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Verificar "
                    + "los datos enviados, por favor contacte al administrador",
                "Error de persistencia de datos", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(EditarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "La fecha de lanzamiento de la "
                    + "pelicula seleccionada es invalida, por favor contacte al administrador",
                    "Error en fecha de lanzamiento", JOptionPane.ERROR_MESSAGE);
        }                 
    }//GEN-LAST:event_jGuardarPActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMISalirActionPerformed

    public void setPeliculaSeleccionada(Pelicula pelicula){
        this.peliculaSeleccionada = pelicula;
        cargarPeliculaSeleccionada(peliculaSeleccionada);
    }
    
    private Pelicula getPeliculaSeleccionada(){
        return this.peliculaSeleccionada;
    }
    
    private int getIndiceCategoria(String categoriaS){
        int indice = 0;
        for (int i = 0; i < jCBCategoriaP.getItemCount(); i++) {
            Categoria categoriaCB = (Categoria)jCBCategoriaP.getItemAt(i);
            if(categoriaS.equals(categoriaCB.getNombre())){
                indice = i;
                break;
            }
        }
        return indice;
    }
    
    private void cargarPeliculaSeleccionada(Pelicula peliculaS){
        String fechaConvertida = (peliculaS.getAño() == null) ? "" : dateUtil.convertirDateAString(peliculaS.getAño());
        String descripcionConvertida = (peliculaS.getDescripcion() == null || 
                "null".equals(peliculaS.getDescripcion())) ? "" : peliculaS.getDescripcion();
        
        int indiceCategoria = this.getIndiceCategoria(peliculaS.getCategoria().getNombre());
        jTFNombreP.setText(peliculaS.getNombre());
        jTFDuracionP.setText(String.valueOf(peliculaS.getDuracion()));
        jTFAñoP.setText(fechaConvertida);
        jTADescripcionP.setText(descripcionConvertida);
       
        jCBCategoriaP.setSelectedIndex(indiceCategoria);
    }
            
    private void cargarCategorias(){
        try{
            categorias = this.getOperacionesPeli().obtenerAllCategorias();
            for(Categoria categoria: categorias){
                this.jCBCategoriaP.addItem(categoria);
            }
        }catch(BDException ex){
            JOptionPane.showMessageDialog(this, "Ocurrio un error al consultar "
                    + "las categorias, mensaje: " + ex.getMessage(), 
                    "Error de persistencia de datos", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private OperacionesPeliculas getOperacionesPeli() {
        if(operacionesPeli == null){
            operacionesPeli = new OperacionesPeliculasImpl();
        }
        return operacionesPeli;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditarPelicula dialog = new EditarPelicula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAñoP;
    private javax.swing.JComboBox jCBCategoriaP;
    private javax.swing.JButton jGuardarP;
    private javax.swing.JLabel jLCategoriaP;
    private javax.swing.JLabel jLDescripcionP;
    private javax.swing.JLabel jLDuracionP;
    private javax.swing.JLabel jLNombreP;
    private javax.swing.JLabel jLabelInformacion;
    private javax.swing.JMenuBar jMBArchivo;
    private javax.swing.JMenu jMFile;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JPanel jPEditarPelicula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTADescripcionP;
    private javax.swing.JTextField jTFAñoP;
    private javax.swing.JTextField jTFDuracionP;
    private javax.swing.JTextField jTFNombreP;
    // End of variables declaration//GEN-END:variables
}
